Frontend:
  extends: .Job_Only
  image: node:10
  stage: frontend
  before_script:
    - npm install
  script:
    - npm test
  after_script:
    - npm run dist
  coverage: /All files\s*\|\s*([\d\.]+)/
